#-------------------nakashima 2015/12/08 edited------------------------#
DeepSparseAutoencoder: Deep_Sparse_Autoencoder.cpp
	mkdir -p DeepSparseAutoencoder
	cp setting.txt sample5D_data.txt DeepSparseAutoencoder/
	g++ -Ofast -Os -w -fopenmp Deep_Sparse_Autoencoder.cpp -o DeepSparseAutoencoder/DSAE.exe #Optimization Option
	#g++ Deep_Sparse_Autoencoder.cpp -o DeepSparseAutoencoder/DeepSparseAutoencoder.exe
